// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $Accordionsparent from "./islands/Accordionsparent.tsx";
import * as $accordions_Accordions from "./islands/accordions/Accordions.tsx";
import * as $accordions_type from "./islands/accordions/type.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Accordionsparent.tsx": $Accordionsparent,
    "./islands/accordions/Accordions.tsx": $accordions_Accordions,
    "./islands/accordions/type.ts": $accordions_type,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
