// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $Accordionsparent from "./islands/Accordionsparent.tsx";
import * as $button_Button from "./islands/button/Button.tsx";
import * as $button_button_variant from "./islands/button/button-variant.ts";
import * as $button_type from "./islands/button/type.ts";
import * as $button_use_button from "./islands/button/use-button.ts";
import * as $global_type from "./islands/global/type.ts";
import * as $icon_component_ClosePassword from "./islands/icon/component/ClosePassword.tsx";
import * as $icon_component_OpenPassword from "./islands/icon/component/OpenPassword.tsx";
import * as $icon_component_PasswordIcon from "./islands/icon/component/PasswordIcon.tsx";
import * as $input_Input from "./islands/input/Input.tsx";
import * as $input_input_variant from "./islands/input/input-variant.ts";
import * as $input_type from "./islands/input/type.ts";
import * as $input_use_input from "./islands/input/use-input.ts";
import * as $theme_use_theme from "./islands/theme/use-theme.ts";
import * as $wrapper from "./islands/wrapper.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Accordionsparent.tsx": $Accordionsparent,
    "./islands/button/Button.tsx": $button_Button,
    "./islands/button/button-variant.ts": $button_button_variant,
    "./islands/button/type.ts": $button_type,
    "./islands/button/use-button.ts": $button_use_button,
    "./islands/global/type.ts": $global_type,
    "./islands/icon/component/ClosePassword.tsx": $icon_component_ClosePassword,
    "./islands/icon/component/OpenPassword.tsx": $icon_component_OpenPassword,
    "./islands/icon/component/PasswordIcon.tsx": $icon_component_PasswordIcon,
    "./islands/input/Input.tsx": $input_Input,
    "./islands/input/input-variant.ts": $input_input_variant,
    "./islands/input/type.ts": $input_type,
    "./islands/input/use-input.ts": $input_use_input,
    "./islands/theme/use-theme.ts": $theme_use_theme,
    "./islands/wrapper.tsx": $wrapper,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
