// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $Accordionsparent from "./islands/Accordionsparent.tsx";
import * as $global_type from "./islands/global/type.ts";
import * as $icon_component_ClosePassword from "./islands/icon/component/ClosePassword.tsx";
import * as $icon_component_Icon from "./islands/icon/component/Icon.tsx";
import * as $icon_component_OpenPassword from "./islands/icon/component/OpenPassword.tsx";
import * as $icon_component_PasswordIcon from "./islands/icon/component/PasswordIcon.tsx";
import * as $inputs_button_Button from "./islands/inputs/button/Button.tsx";
import * as $inputs_button_button_variant from "./islands/inputs/button/button-variant.ts";
import * as $inputs_button_index from "./islands/inputs/button/index.ts";
import * as $inputs_button_type from "./islands/inputs/button/type.ts";
import * as $inputs_button_use_button from "./islands/inputs/button/use-button.ts";
import * as $inputs_checkbox_Checkbox from "./islands/inputs/checkbox/Checkbox.tsx";
import * as $inputs_checkbox_checkbox_variants from "./islands/inputs/checkbox/checkbox-variants.ts";
import * as $inputs_checkbox_index from "./islands/inputs/checkbox/index.ts";
import * as $inputs_checkbox_type from "./islands/inputs/checkbox/type.ts";
import * as $inputs_checkbox_use_checkbox from "./islands/inputs/checkbox/use-checkbox.ts";
import * as $inputs_fieldset_Fieldset from "./islands/inputs/fieldset/Fieldset.tsx";
import * as $inputs_fieldset_fieldset_variants from "./islands/inputs/fieldset/fieldset-variants.ts";
import * as $inputs_fieldset_index from "./islands/inputs/fieldset/index.ts";
import * as $inputs_fieldset_type from "./islands/inputs/fieldset/type.ts";
import * as $inputs_fieldset_use_fieldset from "./islands/inputs/fieldset/use-fieldset.ts";
import * as $inputs_input_Inputs from "./islands/inputs/input/Inputs.tsx";
import * as $inputs_input_index from "./islands/inputs/input/index.ts";
import * as $inputs_input_input_variants from "./islands/inputs/input/input-variants.ts";
import * as $inputs_input_type from "./islands/inputs/input/type.ts";
import * as $inputs_input_use_input from "./islands/inputs/input/use-input.ts";
import * as $inputs_label_Labels from "./islands/inputs/label/Labels.tsx";
import * as $inputs_label_index from "./islands/inputs/label/index.ts";
import * as $inputs_label_label_variant from "./islands/inputs/label/label-variant.ts";
import * as $inputs_label_type from "./islands/inputs/label/type.ts";
import * as $inputs_label_use_label from "./islands/inputs/label/use-label.ts";
import * as $inputs_password_Password from "./islands/inputs/password/Password.tsx";
import * as $inputs_password_index from "./islands/inputs/password/index.ts";
import * as $inputs_password_password_variants from "./islands/inputs/password/password-variants.ts";
import * as $inputs_password_type from "./islands/inputs/password/type.ts";
import * as $inputs_password_use_password from "./islands/inputs/password/use-password.ts";
import * as $inputs_radio_radio_group_RadioGroup from "./islands/inputs/radio/radio-group/RadioGroup.tsx";
import * as $inputs_radio_radio_group_radio_group_variants from "./islands/inputs/radio/radio-group/radio-group-variants.ts";
import * as $inputs_radio_radio_group_type from "./islands/inputs/radio/radio-group/type.ts";
import * as $inputs_radio_radio_group_use_radio_group from "./islands/inputs/radio/radio-group/use-radio-group.ts";
import * as $inputs_radio_radio_radio_variants from "./islands/inputs/radio/radio/radio-variants.ts";
import * as $theme_use_theme from "./islands/theme/use-theme.ts";
import * as $wrapper from "./islands/wrapper.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Accordionsparent.tsx": $Accordionsparent,
    "./islands/global/type.ts": $global_type,
    "./islands/icon/component/ClosePassword.tsx": $icon_component_ClosePassword,
    "./islands/icon/component/Icon.tsx": $icon_component_Icon,
    "./islands/icon/component/OpenPassword.tsx": $icon_component_OpenPassword,
    "./islands/icon/component/PasswordIcon.tsx": $icon_component_PasswordIcon,
    "./islands/inputs/button/Button.tsx": $inputs_button_Button,
    "./islands/inputs/button/button-variant.ts": $inputs_button_button_variant,
    "./islands/inputs/button/index.ts": $inputs_button_index,
    "./islands/inputs/button/type.ts": $inputs_button_type,
    "./islands/inputs/button/use-button.ts": $inputs_button_use_button,
    "./islands/inputs/checkbox/Checkbox.tsx": $inputs_checkbox_Checkbox,
    "./islands/inputs/checkbox/checkbox-variants.ts":
      $inputs_checkbox_checkbox_variants,
    "./islands/inputs/checkbox/index.ts": $inputs_checkbox_index,
    "./islands/inputs/checkbox/type.ts": $inputs_checkbox_type,
    "./islands/inputs/checkbox/use-checkbox.ts": $inputs_checkbox_use_checkbox,
    "./islands/inputs/fieldset/Fieldset.tsx": $inputs_fieldset_Fieldset,
    "./islands/inputs/fieldset/fieldset-variants.ts":
      $inputs_fieldset_fieldset_variants,
    "./islands/inputs/fieldset/index.ts": $inputs_fieldset_index,
    "./islands/inputs/fieldset/type.ts": $inputs_fieldset_type,
    "./islands/inputs/fieldset/use-fieldset.ts": $inputs_fieldset_use_fieldset,
    "./islands/inputs/input/Inputs.tsx": $inputs_input_Inputs,
    "./islands/inputs/input/index.ts": $inputs_input_index,
    "./islands/inputs/input/input-variants.ts": $inputs_input_input_variants,
    "./islands/inputs/input/type.ts": $inputs_input_type,
    "./islands/inputs/input/use-input.ts": $inputs_input_use_input,
    "./islands/inputs/label/Labels.tsx": $inputs_label_Labels,
    "./islands/inputs/label/index.ts": $inputs_label_index,
    "./islands/inputs/label/label-variant.ts": $inputs_label_label_variant,
    "./islands/inputs/label/type.ts": $inputs_label_type,
    "./islands/inputs/label/use-label.ts": $inputs_label_use_label,
    "./islands/inputs/password/Password.tsx": $inputs_password_Password,
    "./islands/inputs/password/index.ts": $inputs_password_index,
    "./islands/inputs/password/password-variants.ts":
      $inputs_password_password_variants,
    "./islands/inputs/password/type.ts": $inputs_password_type,
    "./islands/inputs/password/use-password.ts": $inputs_password_use_password,
    "./islands/inputs/radio/radio-group/RadioGroup.tsx":
      $inputs_radio_radio_group_RadioGroup,
    "./islands/inputs/radio/radio-group/radio-group-variants.ts":
      $inputs_radio_radio_group_radio_group_variants,
    "./islands/inputs/radio/radio-group/type.ts":
      $inputs_radio_radio_group_type,
    "./islands/inputs/radio/radio-group/use-radio-group.ts":
      $inputs_radio_radio_group_use_radio_group,
    "./islands/inputs/radio/radio/radio-variants.ts":
      $inputs_radio_radio_radio_variants,
    "./islands/theme/use-theme.ts": $theme_use_theme,
    "./islands/wrapper.tsx": $wrapper,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
